const en = {
  tracks: 'Tracks',
  ether: 'Ether',
  favorites: 'Favorites',
  login: 'Login',
  password: 'Password',
  executor: 'Executor',
  album: 'Album',
  date: 'Date',
  empty: 'Not filled in',
  name: 'Name',
  random: 'Random order',
  random_count: count => `random of ${count} tracks`,
  settings: 'Settings',
  lang: 'Lang',
  exit: 'Exit',
  auth: 'Authorization',
  english: 'English',
  russian: 'Russian',
  echo_cancellation: 'Echo cancellation',
  images: 'Images',
  theme: 'Theme',
  contrast: 'Contrast',
  background_image: 'Background image',
  yes: 'Yes',
  no: 'No',
  localSound: 'Local sound',
  outputSound: 'Output sound',
  sound: 'Sound',
  mic: 'Mic.',
  localMicrophone: 'Local microphone',
  outputMicrophone: 'Output microphone',
  muted: 'Muted',
  loading: 'Loading..',
  now_playing: 'Now playing',
  added_tracks: count => `Add tracks (total: ${count})`,
  loading_tracks: (loadIndexTrack, loadCountTracks) => `Loading tracks: ${loadIndexTrack} from ${loadCountTracks}`,
  search: 'Search',
  notify: [
    'Greetings, host! I have a few important words for you, my instructions will help you broadcast without problems.',
    'Never try to manually add or change tracks in the working folder! This is dangerous, the files have a structure outside the folder.',
    'The random order of tracks turns on and off automatically after adding a track or sound recording.',
    "Add more tracks so that they don't repeat in random order mode. If you don't use a queue, this random track can be started multiple times."
  ],
  hint_favorites: 'To make a bookmark, drag the audio recording from «Tracks»',
  hint_tracks: 'Just download your first tracks with the .mp3 extension and the broadcast will begin!'
}

const ru = {
  tracks: 'Треки',
  ether: 'Эфир',
  favorites: 'Закладки',
  login: 'Логин',
  password: 'Пароль',
  executor: 'Исполнитель',
  album: 'Альбом',
  date: 'Дата',
  empty: 'Не заполненно',
  name: 'Название',
  random: 'Случайный порядок',
  random_count: count => `случаный из ${count} треков`,
  settings: 'Настройки',
  lang: 'Язык',
  exit: 'Выйти',
  auth: 'Авторизация',
  english: 'Английский',
  russian: 'Русский',
  echo_cancellation: 'Подавление эха',
  images: 'Изображения',
  theme: 'Тема',
  contrast: 'Контраст',
  background_image: 'Фоновая картинка',
  yes: 'Да',
  no: 'Нет',
  localSound: 'Локальный звук',
  outputSound: 'Внешний звук',
  sound: 'Звук',
  mic: 'Микр.',
  localMicrophone: 'Локальный микрофон',
  outputMicrophone: 'Внешний микрофон',
  muted: 'Мут',
  loading: 'Загрузка..',
  now_playing: 'Сейчас играет',
  added_tracks: count => `Добавить треки (всего: ${count})`,
  loading_tracks: (loadIndexTrack, loadCountTracks) => `Загрузка треков: ${loadIndexTrack} из ${loadCountTracks}`,
  search: 'Поиск',
  notify: [
    'Приветствую, ведущий! У меня для тебя есть несколько важных слов, мои инструкции помогут тебе вести трансляцию без проблем.',
    'Никогда не пытайся в ручную добавлять или изменять треки в рабочей папке!',
    'Случайный порядок треков включается и выключается автоматически после добавления трека или звукозаписи.',
    'Добавь больше треков чтоб они не повторялись в режиме случайного порядка.'
  ],
  hint_favorites: 'Чтобы сделать закладку перетяните аудиозапись из «Треки»',
  hint_tracks: 'Просто загрузите свои первые треки с расширением .mp3 и эфир начнется!'
}

module.exports = {
  en,
  ru
}
